# Resume Editor Bot Configuration

# API Settings
api:
  host: "0.0.0.0"
  port: 8000
  debug: true
  cors_origins: ["*"]

# OpenAI Settings
openai:
  model: "gpt-4"
  max_tokens: 2000
  temperature: 0.7

# Vector Database Settings
vector_db:
  embedding_model: "text-embedding-3-small"
  chunk_size: 1000
  chunk_overlap: 200

# File Paths
paths:
  data_dir: "data"
  projects_dir: "data/projects"
  exports_dir: "data/exports"
  resumes_dir: "data/resumes"
  embeddings_dir: "data/embeddings"

# Resume Generation Settings
resume:
  max_projects: 5
  max_skills: 15
  section_order:
    - "summary"
    - "skills"
    - "experience"
    - "education"
    - "publications"
    - "projects"

# Project Analysis Settings
project_analysis:
  relevance_threshold: 0.7
  max_recommendations: 10
  skill_extraction_enabled: true 